reports/routes.py
from reports.utils import report_required, query_execution
from flask import (Blueprint, render_template, session,
                   current_app, request, flash)

from database.sql_provider import SQLProvider
from database.operations import call_proc

from decorators.routes import login_required, role_required


reports_app = Blueprint('reports_app', __name__, template_folder='templates')
sql_provider = SQLProvider('reports/sql')


@reports_app.route('/')
@login_required(session)
@role_required(session)
def reports_index():
    return render_template('reports_index.html',
                           reports=current_app.config['reports_list'])


@reports_app.route('/view-report', methods=['GET', 'POST'])
@login_required(session)
@role_required(session)
@report_required
def view_report(report):
    if request.method == 'POST':
        check_flag, result = query_execution(
            'date', report['sql_statement'], sql_provider)
        if check_flag:
            cost = sum(item['amount'] * item['price'] for item in result)
            return render_template('view_report.html',
                                   name=report['rep_name'],
                                   rep_id=report['rep_id'],
                                   result=result,
                                   cost=cost)
        else:
            flash(result, 'error')
    return render_template('view_report.html',
                           name=report['rep_name'],
                           rep_id=report['rep_id'])


@reports_app.route('/create-report', methods=['GET', 'POST'])
@login_required(session)
@role_required(session)
@report_required
def create_report(report):
    if request.method == 'POST':
        procedure = report['procedure']
        if not procedure:
            flash('Процедура не найдена', 'error')
            return render_template('create_report.html',
                                   name=report['rep_name'],
                                   rep_id=report['rep_id'])
        date = request.form.get('date')

        result = call_proc(
            current_app.config['MYSQL_DB_CONFIG'], procedure, f'{date}-01')

        if result:
            flash(result, 'error')
        else:
            flash('Отчет успешно создан', 'okay')
    return render_template('create_report.html',
                           name=report['rep_name'],
                           rep_id=report['rep_id'])

reports/templates/create_report.html
<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/static/css/styles.css">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700&display=swap" rel="stylesheet">
    <title>Создание отчета</title>
</head>

<body>
    <main>
        <div class="container">
            <div class="container-centered">
                <div class="mytable">
                    <table>
                        <thead>
                            <tr>
                                <th>
                                    <div class="label_page">
                                        {{ name }} <br> (создание)
                                    </div>
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            <form action="{{ url_for('reports_app.create_report') }}" method="POST">
                                <tr>
                                    <td class="no-padding">
                                        <input type="month" name="date" placeholder="Дата" autocomplete="off" required>
                                        <input type="hidden" name="rep_id" value="{{ rep_id }}">
                                    </td>
                                </tr>
                                <tr>
                                    <td style="padding: 0;">
                                        <input type="submit" value="Создать">
                                    </td>
                                </tr>
                            </form>
                            <td style="padding: 0;">
                                <form action="{{ url_for('reports_app.reports_index') }}">
                                    <input type="submit" value="Вернуться к выбору">
                                </form>
                            </td>
                        </tbody>
                    </table>
                </div>
            </div>
            {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
            {% for category, message in messages %}
            <div class="message">
                {% if category == 'okay' %}
                <div class="okay">
                    {{ message }}
                </div>
                {% endif %}
                {% if category == 'error' %}
                <div class="error">
                    {{ message }}
                </div>
                {% endif %}
            </div>
            {% endfor %}
            {% endif %}
            {% endwith %}
        </div>
    </main>

    <div id="loading">
        <div class="spinner"></div>
    </div>
</body>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="/static/js/pageEventHandlers.js"></script>

</html>

reports/templates/reports_index.html
<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/static/css/styles.css">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700&display=swap" rel="stylesheet">
    <title>Отчеты</title>
</head>

<body>
    <main>
        <div class="container">
            <div class="container-centered">
                <div class="mytable">
                    <table>
                        <thead>
                            <tr>
                                <th colspan="2">
                                    <div class="label_page">
                                        Работа с отчетами
                                    </div>
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for report in reports %}
                            <tr>
                                <td rowspan="{{ '1' if session['role'] == 'director' else '2' }}">
                                    {{ report['rep_name'] }}
                                </td>
                                <td class="no-padding">
                                    <form action="{{ url_for('reports_app.view_report') }}">
                                        <input type="hidden" name="rep_id" value="{{ report['rep_id'] }}">
                                        <input type="submit" value="Просмотреть">
                                    </form>
                                </td>
                            </tr>
                            {% if session['role'] == 'manager' %}
                            <tr>
                                <td class="no-padding">
                                    <form action="{{ url_for('reports_app.create_report') }}">
                                        <input type="hidden" name="rep_id" value="{{ report['rep_id'] }}">
                                        <input type="submit" value="Создать">
                                    </form>
                                </td>
                            </tr>
                            {% endif %}
                            {% endfor %}
                            <tr>
                                <td class="no-padding" colspan="3">
                                    <form action="{{ url_for('index_handler') }}" method="GET">
                                        <input type="submit" value="На главную">
                                    </form>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
            {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
            {% for category, message in messages %}
            <div class="message">
                {% if category == 'okay' %}
                <div class="okay">
                    {{ message }}
                </div>
                {% endif %}
                {% if category == 'error' %}
                <div class="error">
                    {{ message }}
                </div>
                {% endif %}
            </div>
            {% endfor %}
            {% endif %}
            {% endwith %}
        </div>
    </main>

    <div id="loading">
        <div class="spinner"></div>
    </div>
</body>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="/static/js/pageEventHandlers.js"></script>

</html>

reports/templates/view_report.html
<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/static/css/styles.css">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700&display=swap" rel="stylesheet">
    <title>Просмотр отчета</title>
</head>

<body>
    <main>
        <div class="container">
            <div class="container-centered">
                <div class="mytable">
                    <table>
                        <thead>
                            <tr>
                                <th>
                                    <div class="label_page">
                                        {{ name }} <br> (просмотр)
                                    </div>
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            <form action="{{ url_for('reports_app.view_report') }}" method="POST">
                                <tr>
                                    <td class="no-padding">
                                        <input type="month" name="date" placeholder="Дата" autocomplete="off" required>
                                        <input type="hidden" name="rep_id" value="{{ rep_id }}">
                                    </td>
                                </tr>
                                <tr>
                                    <td style="padding: 0;">
                                        <input type="submit" value="Просмотреть">
                                    </td>
                                </tr>
                            </form>
                            <td style="padding: 0;">
                                <form action="{{ url_for('reports_app.reports_index') }}">
                                    <input type="submit" value="Вернуться к выбору">
                                </form>
                            </td>
                        </tbody>
                    </table>
                </div>
            </div>
            {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
            {% for category, message in messages %}
            <div class="message">
                {% if category == 'okay' %}
                <div class="okay">
                    {{ message }}
                </div>
                {% endif %}
                {% if category == 'error' %}
                <div class="error">
                    {{ message }}
                </div>
                {% endif %}
            </div>
            {% endfor %}
            {% endif %}
            {% endwith %}
        </div>
        {% if result %}
        <div class="sql-results">
            <div class="label_page">
                {% set months = ["январь", "февраль", "март", "апрель", "май", "июнь", "июль", "август", "сентябрь",
                "октябрь", "ноябрь", "декабрь"] %}
                {{ name }} за {{ months[result[0]['rep_month'] - 1] }} {{ result[0]['rep_year'] }}г.
            </div>
            {% if rep_id == '1' %}
            <div class="mytable-for-results">
                <table>
                    <thead>
                        <tr>
                            <th>Название поставщика</th>
                            <th>Город поставщика</th>
                            <th>Название товара</th>
                            <th>Количество</th>
                            <th>Цена</th>
                            <th>Дата поставки</th>
                        </tr>
                    <tbody>
                        {% for item in result %}
                        <tr>
                            <td>{{ item['sh_name'] }}</td>
                            <td>{{ item['sh_city'] }}</td>
                            <td>{{ item['pr_name'] }}</td>
                            <td>{{ item['amount'] }}</td>
                            <td>{{ item['price'] }}</td>
                            <td>{{ item['in_date'] }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                    <tfoot>
                        <tr>
                            <td>
                                В выбранную дату объем заказанных у поставщиков заготовок
                                <strong>{{cost}}₽</strong>
                            </td>
                        </tr>
                        <tr>
                            <td class="no-padding" style="background-color: var(--register-color);">
                                <input type="submit" value="Вернуться к вводу"
                                    onclick="document.querySelector('.container').scrollIntoView({ behavior: 'smooth' })">
                            </td>
                        </tr>
                    </tfoot>
                </table>
            </div>
            {% endif %}
            <!-- {% if rep_id == '2' %}
            <div class="mytable-for-results">
                <table>
                    <thead>
                        <tr>
                            <th></th>
                            <th></th>
                            <th></th>
                            <th></th>
                        </tr>
                    <tbody>
                        {% for item in result %}
                        <tr>
                            <td>{{ item[''] }}</td>
                            <td>{{ item[''] }}</td>
                            <td>{{ item[''] }} шт.</td>
                            <td>{{ item[''] }}₽</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                    <tfoot>
                        <tr>
                            <td>
                                В выбранную дату объем заказанных пользователями товаров составил
                                <strong>{{cost}}₽</strong>
                            </td>
                        </tr>
                        <tr>
                            <td class="no-padding" style="background-color: var(--register-color);">
                                <input type="submit" value="Вернуться к вводу"
                                    onclick="document.querySelector('.container').scrollIntoView({ behavior: 'smooth' })">
                            </td>
                        </tr>
                    </tfoot>
                </table>
            </div>
            {% endif %} -->
        </div>
        {% endif %}
    </main>

    <div id="loading">
        <div class="spinner"></div>
    </div>
</body>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="/static/js/pageEventHandlers.js"></script>

</html>