basket/routes.py
from flask import (Blueprint, render_template, request,
                   current_app, flash, session, redirect, url_for)
from database.sql_provider import SQLProvider
from database.operations import select_from_db, insert_into_db
from database.connection import DBContextManager

from decorators.routes import login_required, role_required

from datetime import date

basket_app = Blueprint('basket_app', __name__, template_folder='templates')
sql_provider = SQLProvider('basket/sql')


@basket_app.route('/', methods=['GET', 'POST'])
@login_required(session)
@role_required(session)
def basket_index():
    if not session.get('basket'):
        session['basket'] = []

    sql_statement = sql_provider.get('select_all_details.sql', {})
    result = select_from_db(
        current_app.config['MYSQL_DB_CONFIG'], sql_statement)

    if request.method == 'POST':
        detail_id = request.form['code']
        price = request.form['price']
        quantity = int(request.form['quantity'])

        for item in session['basket']:
            if item['code'] == detail_id and item['price'] == price:
                item['quantity'] += quantity
                flash('Добавлено в накладную', 'okay')
                break
        else:
            session['basket'].append(
                {'code': request.form['code'],
                    'name': request.form['name'],
                    'material': request.form['material'],
                    'weight': request.form['weight'],
                    'price': price,
                    'quantity': quantity})
            flash('Добавлено в накладную', 'okay')
        session.modified = True

    return render_template('basket_index.html',
                           count=len(session['basket']),
                           result=result)


@basket_app.route('/show', methods=['GET'])
@login_required(session)
@role_required(session)
def show_basket_handler():
    basket = session.get('basket')
    if len(basket) == 0:
        flash('Накладная пуста', 'error')
        return redirect(url_for('basket_app.basket_index'))
    else:
        cost = 0
        for item in basket:
            cost += float(item['price']) * int(item['quantity'])
        return render_template('show_basket.html', basket=basket, cost=cost)


@basket_app.route('/delete-all', methods=['GET', 'POST'])
@login_required(session)
@role_required(session)
def delete_all_handler():
    session['basket'] = []
    session.modified = True
    flash('Накладная очищена', 'okay')
    return redirect(url_for('basket_app.basket_index'))


@basket_app.route('/delete-current', methods=['POST'])
@login_required(session)
@role_required(session)
def delete_current_handler():
    basket = session.get('basket', [])
    session['basket'] = [product for product in basket if product['code']
                         != request.form.get('code')]
    session.modified = True

    return redirect(url_for('basket_app.show_basket_handler'))


@basket_app.route('/create-order', methods=['POST'])
@login_required(session)
@role_required(session)
def create_order_handler():
    username = session.get('user')
    basket = session.get('basket', [])
    date_now = date.today()

    sql_statement = sql_provider.get('select_sh_id.sql', {
        'username': username})
    sh_id = select_from_db(
        current_app.config['MYSQL_DB_CONFIG'], sql_statement)[0]['sh_id']

    sql_statement = sql_provider.get('create_invoice.sql', {
        'sh_id': sh_id,
        'date': date_now})
    insert_into_db(
        current_app.config['MYSQL_DB_CONFIG'], sql_statement)

    sql_statement = sql_provider.get('select_in_id.sql', {})
    in_id = select_from_db(
        current_app.config['MYSQL_DB_CONFIG'], sql_statement)[0]['in_id']

    with DBContextManager(current_app.config['MYSQL_DB_CONFIG']) as db:
        for item in basket:
            sql_statement = sql_provider.get('create_order.sql', {
                'quantity': int(item['quantity']),
                'price': item['price'],
                'in_id': in_id,
                'code': item['code']
            })
            db.execute(sql_statement)

    session['basket'] = []
    session.modified = True
    flash('Накладная успешно создана', 'okay')
    return redirect(url_for('basket_app.basket_index'))


@basket_app.route('/check-invoices', methods=['GET', 'POST'])
@login_required(session)
@role_required(session)
def check_invoices():
    sql_statement = sql_provider.get('select_invoices.sql', {})
    result = select_from_db(
        current_app.config['MYSQL_DB_CONFIG'], sql_statement)

    if request.method == 'POST':
        code = request.form['code']
        sql_statement = sql_provider.get('update_invoices.sql', {'code': code})
        insert_into_db(current_app.config['MYSQL_DB_CONFIG'], sql_statement)
        flash('Статус накладной изменен', 'okay')
        return redirect(url_for('basket_app.check_invoices'))

    return render_template('invoices.html', result=result)

basket/templates/basket_index.html
<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/static/css/styles.css">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700&display=swap" rel="stylesheet">
    <title>Ассортимент</title>
</head>

<body>
    <main>
        <div class="container">
            <div class="container-centered">
                <div class="mytable-for-results">
                    <table>
                        <thead>
                            <tr>
                                <th colspan=8">
                                    <div class="label_page">
                                        Формирование заказа на поставку
                                    </div>
                                </th>
                            </tr>
                            <tr>
                                <th class='no-padding' colspan="8">
                                    <input type="text" id="search" placeholder="Поиск по названию детали"
                                        autocomplete="off">
                                </th>
                            </tr>
                            <tr>
                                <th>Наименование</th>
                                <th>Вес</th>
                                <th>Материал</th>
                                <th>Количество на складе</th>
                                <th>Цена за единицу</th>
                                <th>Количество для накладной</th>
                                <th>Добавление</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for row in result %}
                            <tr>
                                <td>
                                    {{ row['pr_name'] }}
                                </td>
                                <td>
                                    {{ row['pr_weight'] }}
                                </td>
                                <td>
                                    {{ row['pr_material'] }}
                                </td>
                                <td>
                                    {{ row['st_amount'] }}
                                </td>
                                <td>
                                    {{ row['price'] }}
                                </td>
                                <form action="{{ url_for('basket_app.basket_index') }}" method="POST">
                                    <td class="no-padding" style="background-color: var(--register-color);">
                                        <input type="number" name="quantity" value="1" min="1" autocomplete="off"
                                            required>
                                    </td>
                                    <td class="no-padding" style="background-color: var(--register-color);">
                                        <input type="hidden" name="code" value="{{ row['code'] }}">
                                        <input type="hidden" name="name" value="{{ row['pr_name'] }}">
                                        <input type="hidden" name="material" value="{{ row['pr_material'] }}">
                                        <input type="hidden" name="weight" value="{{ row['pr_weight'] }}">
                                        <input type="hidden" name="price" value="{{ row['price'] }}">
                                        <input type="submit" value="Добавить">
                                    </td>
                                </form>
                            </tr>
                            {% endfor %}
                        </tbody>
                        <tfoot>
                            <tr>
                                <td class="no-padding" style="background-color: var(--register-color);">
                                    <form action="{{ url_for('basket_app.show_basket_handler') }}">
                                        <input type="submit" value="Просмотр накладной ({{ count }})">
                                    </form>
                                </td>
                            </tr>
                            <tr>
                                <td class="no-padding" style="background-color: var(--register-color);">
                                    <form action="/">
                                        <input type="submit" value="На главную">
                                    </form>
                                </td>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
            {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
            {% for category, message in messages %}
            <div class="message">
                {% if category == 'okay' %}
                <div class="okay">
                    {{ message }}
                </div>
                {% endif %}
                {% if category == 'error' %}
                <div class="error">
                    {{ message }}
                </div>
                {% endif %}
            </div>
            {% endfor %}
            {% endif %}
            {% endwith %}
        </div>
    </main>

    <div id="loading">
        <div class="spinner"></div>
    </div>
</body>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="/static/js/pageEventHandlers.js"></script>

</html>

basket/templates/invoices.html
<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/static/css/styles.css">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700&display=swap" rel="stylesheet">
    <title>Просмотр накладной</title>
</head>

<body>
    <main>
        <div class="container">
            <div class="container-centered">
                <div class="mytable-for-results">
                    <table>
                        <thead>
                            <tr>
                                <th colspan="7">
                                    <div class="label_page">
                                        Накладная
                                    </div>
                                </th>
                            </tr>
                            <tr>
                                <th>Дата формирования накладной</th>
                                <th>Наименование поставщика</th>
                                <th>Статус</th>
                                <th>Подтвердить накладную</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for row in result %}
                            <tr>
                                <td>
                                    {{ row['in_date'] }}
                                </td>
                                <td>
                                    {{ row['sh_name'] }}
                                </td>
                                <td>
                                    {{ row['status'] }}
                                </td>
                                </td>
                                <form action="{{ url_for('basket_app.check_invoices') }}" method="POST">
                                    <td class="no-padding" style="background-color: var(--register-color);">
                                        <input type="submit" value="Принять">
                                        <input type="hidden" name="code" value="{{ row['in_id'] }}">
                                    </td>
                                </form>
                            </tr>
                            {% endfor %}
                        </tbody>
                        <tfoot>
                            <tr>
                                <td class="no-padding" style="background-color: var(--register-color);">
                                    <form action="/">
                                        <input type="submit" value="Вернуться к главному меню">
                                    </form>
                                </td>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
            {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
            {% for category, message in messages %}
            <div class="message">
                {% if category == 'okay' %}
                <div class="okay">
                    {{ message }}
                </div>
                {% endif %}
                {% if category == 'error' %}
                <div class="error">
                    {{ message }}
                </div>
                {% endif %}
            </div>
            {% endfor %}
            {% endif %}
            {% endwith %}
        </div>
    </main>

    <div id="loading">
        <div class="spinner"></div>
    </div>
</body>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="/static/js/pageEventHandlers.js"></script>

</html>

basket/templates/show_basket.html
<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/static/css/styles.css">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700&display=swap" rel="stylesheet">
    <title>Просмотр накладной</title>
</head>

<body>
    <main>
        <div class="container">
            <div class="container-centered">
                <div class="mytable-for-results">
                    <table>
                        <thead>
                            <tr>
                                <th colspan="7">
                                    <div class="label_page">
                                        Накладная
                                    </div>
                                </th>
                            </tr>
                            <tr>
                                <th>Код заготовки</th>
                                <th>Наименование</th>
                                <th>Материал</th>
                                <th>Вес</th>
                                <th>Цена за единицу</th>
                                <th>Количество</th>
                                <th>Удаление</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for row in basket %}
                            <tr>
                                <td>
                                    {{ row['code'] }}
                                </td>
                                <td>
                                    {{ row['name'] }}
                                </td>
                                <td>
                                    {{ row['material'] }}
                                </td>
                                <td>
                                    {{ row['weight'] }} гр.
                                </td>
                                <td>
                                    {{ row['price'] }}₽.
                                </td>
                                <td>
                                    {{ row['quantity'] }} шт.
                                </td>
                                <form action="{{ url_for('basket_app.delete_current_handler') }}" method="POST">
                                    <td class="no-padding" style="background-color: var(--register-color);">
                                        <input type="submit" value="Удалить">
                                        <input type="hidden" name="code" value="{{ row['code'] }}">
                                    </td>
                                </form>
                            </tr>
                            {% endfor %}
                        </tbody>
                        <tfoot>
                            <tr>
                                <td>
                                    Общая сумма накладной составила
                                    <strong>{{cost}}₽</strong>
                                </td>
                            </tr>
                            <tr>
                                <td class="no-padding" style="background-color: var(--register-color);">
                                    <form action="{{ url_for('basket_app.create_order_handler') }}" method="POST">
                                        <input type="submit" value="Сформировать накладную">
                                    </form>
                                </td>
                            </tr>
                            <tr>
                                <td class="no-padding" style="background-color: var(--register-color);">
                                    <form action="{{  url_for('basket_app.delete_all_handler') }}" method="POST">
                                        <input type="submit" value="Очистить всю накладную">
                                    </form>
                                </td>
                            </tr>
                            <tr>
                                <td class="no-padding" style="background-color: var(--register-color);">
                                    <form action="{{ url_for('basket_app.basket_index') }}">
                                        <input type="submit" value="Вернуться к выбору">
                                    </form>
                                </td>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
            {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
            {% for category, message in messages %}
            <div class="message">
                {% if category == 'okay' %}
                <div class="okay">
                    {{ message }}
                </div>
                {% endif %}
                {% if category == 'error' %}
                <div class="error">
                    {{ message }}
                </div>
                {% endif %}
            </div>
            {% endfor %}
            {% endif %}
            {% endwith %}
        </div>
    </main>

    <div id="loading">
        <div class="spinner"></div>
    </div>
</body>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="/static/js/pageEventHandlers.js"></script>

</html>