queries/routes.py
from typing import Tuple, Any
from flask import (
    Blueprint,
    render_template,
    request,
    current_app,
    flash,
    session
)

from database.sql_provider import SQLProvider
from database.operations import select_from_db, insert_into_db

from decorators.routes import login_required, role_required

queries_app: Blueprint = Blueprint(
    'queries_app', __name__, template_folder='templates')
sql_provider: SQLProvider = SQLProvider('queries/sql')


@queries_app.route('/')
@login_required(session)
@role_required(session)
def queries_index():
    """
    Обрабатывает главную страницу запросов.
    """
    return render_template('queries_index.html', role=session['role'])


def query_execution(key, sql_statement_name):
    """
    Выполняет SQL-запрос и возвращает результат.
    """
    data = request.form.get(key)

    if not data:
        return False, "Данные не введены"

    sql_statement = sql_provider.get(sql_statement_name, {key: data})
    result = select_from_db(
        current_app.config['MYSQL_DB_CONFIG'], sql_statement)

    if not result:
        return False, "Нет результатов"

    return True, result


@queries_app.route('/show-balance', methods=['GET', 'POST'])
@login_required(session)
@role_required(session)
def show_balance():
    if request.method == 'GET':
        return render_template('show_balance.html')
    else:
        check_flag, result = query_execution(
            'name', 'show_balance.sql')

        if check_flag:
            return render_template('show_balance.html', result=result)
        else:
            flash(result, 'error')
            return render_template('show_balance.html', message=result)


@queries_app.route('/show-invoice-by-date', methods=['GET', 'POST'])
@login_required(session)
@role_required(session)
def show_invoice_by_month():
    if request.method == 'GET':
        return render_template('show_invoice_by_month.html')
    else:
        check_flag, result = query_execution(
            'date', 'show_invoice_by_month.sql')

        if check_flag:
            return render_template('show_invoice_by_month.html', result=result)
        else:
            flash(result, 'error')
            return render_template('show_invoice_by_month.html', message=result)


@queries_app.route('/show-history', methods=['GET', 'POST'])
@login_required(session)
@role_required(session)
def show_history_by_shipper():
    if request.method == 'GET':
        return render_template('show_history_by_shipper.html')
    else:
        check_flag, result = query_execution(
            'name', 'show_history_by_shipper.sql')

        if check_flag:
            return render_template('show_history_by_shipper.html', result=result)
        else:
            flash(result, 'error')
            return render_template('show_history_by_shipper.html', message=result)


@queries_app.route('/show-shippers', methods=['GET', 'POST'])
@login_required(session)
@role_required(session)
def search_shippers_by_city():
    if request.method == 'GET':
        return render_template('search_shippers_by_city.html')
    else:
        check_flag, result = query_execution(
            'city', 'search_shippers_by_city.sql')

        if check_flag:
            return render_template('search_shippers_by_city.html', result=result)
        else:
            flash(result, 'error')
            return render_template('search_shippers_by_city.html', message=result)


@queries_app.route('/search-by-material', methods=['GET', 'POST'])
@login_required(session)
@role_required(session)
def search_by_material_handler():
    if request.method == 'GET':
        return render_template('search_detail_by_material.html')
    else:
        check_flag, result = query_execution(
            'material', 'search_detail_by_material.sql')

        if check_flag:
            return render_template('search_detail_by_material.html', result=result)
        return render_template('search_detail_by_material.html', message=result)

queries/templates/base_for_search.html
<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/static/css/styles.css">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700&display=swap" rel="stylesheet">
    <link rel="icon" href="/static/images/icon.svg" type="image/x-icon">
    <title>{% block title %}{% endblock %}</title>
</head>

<body>
    <main>
        <div class="container">
            <div class="container-centered">
                <div class="mytable">
                    <table>
                        <thead>
                            <tr>
                                <th>
                                    <div class="label_page">
                                        {% block name_of_search %}{% endblock %}
                                    </div>
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            {% block form %}{% endblock %}
                            <td style="padding: 0;">
                                <form action="{{ url_for('queries_app.queries_index') }}">
                                    <input type="submit" value="Вернуться к выбору">
                                </form>
                            </td>
                        </tbody>
                    </table>
                </div>
            </div>
            {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
            {% for category, message in messages %}
            <div class="message">
                {% if category == 'okay' %}
                <div class="okay">
                    {{ message }}
                </div>
                {% endif %}
                {% if category == 'error' %}
                <div class="error">
                    {{ message }}
                </div>
                {% endif %}
            </div>
            {% endfor %}
            {% endif %}
            {% endwith %}
        </div>
        {% if result %}
        <div class="sql-results">
            <div class="label_page">
                Результаты запроса
            </div>
            <div class="mytable-for-results">
                <table>
                    <thead>
                        {% block table_header %}{% endblock %}
                    <tbody>
                        {% block table_body %}{% endblock %}
                    </tbody>
                    <tfoot>
                        <tr>
                            <td class="no-padding" style="background-color: var(--register-color);">
                                <input type="submit" value="Вернуться к вводу"
                                    onclick="document.querySelector('.container').scrollIntoView({ behavior: 'smooth' })">
                            </td>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
        {% endif %}
    </main>

    <div id="loading">
        <div class="spinner"></div>
    </div>
</body>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="/static/js/pageEventHandlers.js"></script>

</html>

queries/templates/queries_index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/static/css/styles.css">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700&display=swap" rel="stylesheet">
    <link rel="icon" href="/static/images/icon.svg" type="image/x-icon">
    <title>Выполнение запроса</title>
</head>

<body>
    <main>
        <div class="container">
            <div class="container-centered">
                <div class="mytable">
                    <table>
                        <thead>
                            <tr>
                                <th>
                                    <div class="label_page">
                                        Выполнение запроса
                                    </div>
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            {% if session['role'] == 'merchandiser' %}
                            <tr>
                                <td class="no-padding">
                                    <form action="{{ url_for('queries_app.show_balance') }}" method="GET">
                                        <input type="submit" value="Показать остаток на складе">
                                    </form>
                                </td>
                            </tr>
                            <tr>
                                <td class="no-padding">
                                    <form action="{{ url_for('queries_app.show_invoice_by_month') }}" method="GET">
                                        <input type="submit" value="Показать список поставок">
                                    </form>
                                </td>
                            </tr>
                            <tr>
                                <td class="no-padding">
                                    <form action="{{ url_for('queries_app.search_by_material_handler') }}" method="GET">
                                        <input type="submit" value="Показать детали определенного материала">
                                    </form>
                                </td>
                            </tr>
                            {% endif %}
                            {% if session['role'] == 'logist' %}
                            <tr>
                                <td class="no-padding">
                                    <form action="{{ url_for('queries_app.search_shippers_by_city') }}" method="GET">
                                        <input type="submit" value="Показать поставщиков по городу">
                                    </form>
                                </td>
                            </tr>
                            <tr>
                                <td class="no-padding">
                                    <form action="{{ url_for('queries_app.show_history_by_shipper') }}" method="GET">
                                        <input type="submit" value="Показать историю поставок">
                                    </form>
                                </td>
                            </tr>
                            {% endif %}
                            <tr>
                                <td class="no-padding">
                                    <form action="{{ url_for('index_handler') }}" method="GET">
                                        <input type="submit" value="На главную">
                                    </form>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
            {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
            {% for category, message in messages %}
            <div class="message">
                {% if category == 'okay' %}
                <div class="okay">
                    {{ message }}
                </div>
                {% endif %}
                {% if category == 'error' %}
                <div class="error">
                    {{ message }}
                </div>
                {% endif %}
            </div>
            {% endfor %}
            {% endif %}
            {% endwith %}
        </div>
    </main>

    <div id="loading">
        <div class="spinner"></div>
    </div>
</body>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="/static/js/pageEventHandlers.js"></script>

</html>

queries/templates/search_detail_by_material.html
{% extends "base_for_search.html" %}
{% block title %}Показать детали{% endblock %}
{% block name_of_search %}Показать детали определенного материала{% endblock %}

{% block form %}
<form action="{{ url_for('queries_app.search_by_material_handler') }}" method="POST">
    <tr>
        <td class="no-padding">
            <input type="text" name="material" placeholder="Материал" autocomplete="off">
        </td>
    </tr>
    <tr>
        <td style="padding: 0;">
            <input type="submit" value="Найти">
        </td>
    </tr>
</form>
{% endblock %}

{% block table_header %}
<tr>
    <th>Наименование</th>
    <th>Вес</th>
    <th>Материал</th>
    <th>Цена</th>
    <th>Количество на складе</th>
    <th>Дата обновления</th>
</tr>
{% endblock %}


{% block table_body %}
{% for item in result %}
<tr>
    <td>{{ item['pr_name'] }}</td>
    <td>{{ item['pr_weight'] }}</td>
    <td>{{ item['pr_material'] }}</td>
    <td>{{ item['st_price'] }}₽</td>
    <td>{{ item['st_amount'] }} шт.</td>
    <td>{{ item['st_date'] }}</td>
</tr>
{% endfor %}
{% endblock %}

queries/templates/search_shippers_by_city.html
{% extends "base_for_search.html" %}
{% block title %}Поиск{% endblock %}
{% block name_of_search %}Показать поставщиков по городу{% endblock %}

{% block form %}
<form action="{{ url_for('queries_app.search_shippers_by_city') }}" method="POST">
    <tr>
        <td class="no-padding">
            <input type="text" name="city" placeholder="Город" autocomplete="off" required minlength="3">
        </td>
    </tr>
    <tr>
        <td style="padding: 0;">
            <input type="submit" value="Найти">
        </td>
    </tr>
</form>
{% endblock %}

{% block table_header %}
<tr>
    <th>Название</th>
    <th>Город</th>
    <th>Дата заключения контракта</th>
    <th>Телефон</th>
</tr>
{% endblock %}

{% block table_body %}
{% for item in result %}
<tr>
    <td>{{ item['sh_name'] }}</td>
    <td>{{ item['sh_city'] }}</td>
    <td>{{ item['sh_date'] }}</td>
    <td>{{ item['sh_phone'] }}</td>
</tr>
{% endfor %}
{% endblock %}

queries/templates/show_balance.html
{% extends "base_for_search.html" %}
{% block title %}Показать{% endblock %}
{% block name_of_search %}Показать остаток на складе{% endblock %}

{% block form %}
<form action="{{ url_for('queries_app.show_balance') }}" method="POST">
    <tr>
        <td class="no-padding">
            <input type="text" name="name" placeholder="Название" autocomplete="off" required minlength="3">
        </td>
    </tr>
    <tr>
        <td style="padding: 0;">
            <input type="submit" value="Найти">
        </td>
    </tr>
</form>
{% endblock %}

{% block table_header %}
<tr>
    <th>Название заготовки</th>
    <th>Вес заготовки</th>
    <th>Количество на складе</th>
    <th>Цена за единицу</th>
    <th>Дата обновления</th>
</tr>
{% endblock %}

{% block table_body %}
{% for item in result %}
<tr>
    <td>{{ item['pr_name'] }}</td>
    <td>{{ item['pr_weight'] }}</td>
    <td>{{ item['st_amount'] }}</td>
    <td>{{ item['st_price'] }}</td>
    <td>{{ item['max'] }}</td>
</tr>
{% endfor %}
{% endblock %}

queries/templates/show_history_by_shipper.html
{% extends "base_for_search.html" %}
{% block title %}Поиск{% endblock %}
{% block name_of_search %}Показать историю поставок{% endblock %}

{% block form %}
<form action="{{ url_for('queries_app.show_history_by_shipper') }}" method="POST">
    <tr>
        <td class="no-padding">
            <input type="text" name="name" placeholder="Название" autocomplete="off" required minlength="3">
        </td>
    </tr>
    <tr>
        <td style="padding: 0;">
            <input type="submit" value="Найти">
        </td>
    </tr>
</form>
{% endblock %}

{% block table_header %}
<tr>
    <th>Название поставщика</th>
    <th>Город поставщика</th>
    <th>Телефон поставщика</th>
    <th>Название заготовки</th>
    <th>Материал заготовки</th>
    <th>Количество</th>
    <th>Цена за единицу</th>
</tr>
{% endblock %}

{% block table_body %}
{% for item in result %}
<tr>
    <td>{{ item['sh_name'] }}</td>
    <td>{{ item['sh_city'] }}</td>
    <td>{{ item['sh_phone'] }}</td>
    <td>{{ item['pr_name'] }}</td>
    <td>{{ item['pr_material'] }}</td>
    <td>{{ item['il_quantity'] }}₽</td>
    <td>{{ item['il_price'] }}</td>
</tr>
{% endfor %}
{% endblock %}

queries/templates/show_invoice_by_month.html
{% extends "base_for_search.html" %}
{% block title %}Поиск{% endblock %}
{% block name_of_search %}Показать список поставок{% endblock %}

{% block form %}
<form action="{{ url_for('queries_app.show_invoice_by_month') }}" method="POST">
    <tr>
        <td class="no-padding">
            <input type="month" name="date" placeholder="Дата заказа" autocomplete="off" required minlength="3">
        </td>
    </tr>
    <tr>
        <td style="padding: 0;">
            <input type="submit" value="Найти">
        </td>
    </tr>
</form>
{% endblock %}

{% block table_header %}
<tr>
    <th>Дата</th>
    <th>Название</th>
    <th>Сумма</th>
</tr>
{% endblock %}

{% block table_body %}
{% for item in result %}
<tr>
    <td>{{ item['in_date'] }}</td>
    <td>{{ item['sh_name'] }}</td>
    <td>{{ item['total_cost'] }}</td>
</tr>
{% endfor %}
{% endblock %}