access/routes.py
from flask import (Blueprint, render_template, request,
                   session, current_app, redirect, flash, url_for)
from database.sql_provider import SQLProvider
from database.operations import select_from_db, insert_into_db

from datetime import datetime
from decorators.routes import login_required, role_required


access_app = Blueprint('access_app', __name__, template_folder='templates')
sql_provider = SQLProvider('access/sql')


@access_app.route('/', methods=['GET'])
def access_index():
    return render_template('access_index.html')


def user_exists(username):
    sql_statement = sql_provider.get(
        'check_user_doesnt_exist.sql', {'username': username})
    result = select_from_db(
        current_app.config['MYSQL_DB_CONFIG'], sql_statement)
    return bool(result)


@access_app.route('/login', methods=['POST'])
def login_handler():
    name, password = request.form['username'], request.form['password']
    data = {'user': name, 'password': password}

    if not user_exists(name):
        flash('Неправильный логин или пароль', 'error')
        return render_template('access_index.html')

    sql_statement = sql_provider.get(
        'check_role.sql',
        {'login': data['user'], 'password': data['password']})
    connect = select_from_db(
        current_app.config['MYSQL_DB_CONFIG'], sql_statement)

    if connect:
        session['user'] = name
        session['password'] = password
        session['is_auth'] = True
        session['role'] = connect[0]['role']
    else:
        flash('Неправильный логин или пароль', 'error')
        return render_template('access_index.html')
    return redirect('/')


@access_app.route('/register', methods=['GET', 'POST'])
def register_handler():
    if request.method == 'GET':
        return render_template('register.html')
    elif request.method == 'POST':
        username = request.form['username']
        password = request.form['password']

        if user_exists(username):
            flash('Пользователь уже существует', 'error')
            return render_template('register.html')

        sql_statement = sql_provider.get(
            'add_user.sql', {'username': username, 'password': password})
        insert_into_db(
            current_app.config['MYSQL_DB_CONFIG'], sql_statement)
        flash('Пользователь успешно добавлен', 'okay')
        return redirect(url_for('access_app.access_index'))


@login_required(session)
@access_app.route('/logout', methods=['GET'])
def logout_handler():
    session.clear()
    return redirect('/')


@login_required(session)
@role_required(session)
@access_app.route('/account', methods=['GET', 'POST'])
def personal_account():
    if request.method == 'GET':
        sql_statement = sql_provider.get(
            'get_user_info.sql', {'username': session['user']})
        result = select_from_db(
            current_app.config['MYSQL_DB_CONFIG'], sql_statement)

        user_info = {'username': session['user']}

        if result:
            user_info['name'] = result[0]['name']
            user_info['city'] = result[0]['city']
            user_info['sh_date'] = result[0]['sh_date']
            user_info['sh_phone'] = result[0]['sh_phone']
        return render_template('account.html', user_info=user_info)

    if request.method == 'POST':
        name = request.form.get('name')
        city = request.form.get('city')
        phone_number = request.form.get('phone')
        date_now = datetime.now().strftime('%Y-%m-%d')

        sql_statement = sql_provider.get('add_info_about_user.sql',
                                         {
                                             'username': session['user'],
                                             'name': name,
                                             'city': city,
                                             'sh_date': date_now,
                                             'sh_phone': phone_number
                                         }
                                         )
        insert_into_db(
            current_app.config['MYSQL_DB_CONFIG'], sql_statement)
        flash('Информация успешно добавлена', 'okay')
        return redirect(url_for('access_app.personal_account'))

queries/routes.py
from typing import Tuple, Any
from flask import (
    Blueprint,
    render_template,
    request,
    current_app,
    flash,
    session
)

from database.sql_provider import SQLProvider
from database.operations import select_from_db, insert_into_db

from decorators.routes import login_required, role_required

queries_app: Blueprint = Blueprint(
    'queries_app', __name__, template_folder='templates')
sql_provider: SQLProvider = SQLProvider('queries/sql')


@queries_app.route('/')
@login_required(session)
@role_required(session)
def queries_index():
    """
    Обрабатывает главную страницу запросов.
    """
    return render_template('queries_index.html', role=session['role'])


def query_execution(key, sql_statement_name):
    """
    Выполняет SQL-запрос и возвращает результат.
    """
    data = request.form.get(key)

    if not data:
        return False, "Данные не введены"

    sql_statement = sql_provider.get(sql_statement_name, {key: data})
    result = select_from_db(
        current_app.config['MYSQL_DB_CONFIG'], sql_statement)

    if not result:
        return False, "Нет результатов"

    return True, result


@queries_app.route('/show-balance', methods=['GET', 'POST'])
@login_required(session)
@role_required(session)
def show_balance():
    if request.method == 'GET':
        return render_template('show_balance.html')
    else:
        check_flag, result = query_execution(
            'name', 'show_balance.sql')

        if check_flag:
            return render_template('show_balance.html', result=result)
        else:
            flash(result, 'error')
            return render_template('show_balance.html', message=result)


@queries_app.route('/show-invoice-by-date', methods=['GET', 'POST'])
@login_required(session)
@role_required(session)
def show_invoice_by_month():
    if request.method == 'GET':
        return render_template('show_invoice_by_month.html')
    else:
        check_flag, result = query_execution(
            'date', 'show_invoice_by_month.sql')

        if check_flag:
            return render_template('show_invoice_by_month.html', result=result)
        else:
            flash(result, 'error')
            return render_template('show_invoice_by_month.html', message=result)


@queries_app.route('/show-history', methods=['GET', 'POST'])
@login_required(session)
@role_required(session)
def show_history_by_shipper():
    if request.method == 'GET':
        return render_template('show_history_by_shipper.html')
    else:
        check_flag, result = query_execution(
            'name', 'show_history_by_shipper.sql')

        if check_flag:
            return render_template('show_history_by_shipper.html', result=result)
        else:
            flash(result, 'error')
            return render_template('show_history_by_shipper.html', message=result)


@queries_app.route('/show-shippers', methods=['GET', 'POST'])
@login_required(session)
@role_required(session)
def search_shippers_by_city():
    if request.method == 'GET':
        return render_template('search_shippers_by_city.html')
    else:
        check_flag, result = query_execution(
            'city', 'search_shippers_by_city.sql')

        if check_flag:
            return render_template('search_shippers_by_city.html', result=result)
        else:
            flash(result, 'error')
            return render_template('search_shippers_by_city.html', message=result)


@queries_app.route('/search-by-material', methods=['GET', 'POST'])
@login_required(session)
@role_required(session)
def search_by_material_handler():
    if request.method == 'GET':
        return render_template('search_detail_by_material.html')
    else:
        check_flag, result = query_execution(
            'material', 'search_detail_by_material.sql')

        if check_flag:
            return render_template('search_detail_by_material.html', result=result)
        return render_template('search_detail_by_material.html', message=result)

reports/routes.py
from reports.utils import report_required, query_execution
from flask import (Blueprint, render_template, session,
                   current_app, request, flash)

from database.sql_provider import SQLProvider
from database.operations import call_proc

from decorators.routes import login_required, role_required


reports_app = Blueprint('reports_app', __name__, template_folder='templates')
sql_provider = SQLProvider('reports/sql')


@reports_app.route('/')
@login_required(session)
@role_required(session)
def reports_index():
    return render_template('reports_index.html',
                           reports=current_app.config['reports_list'])


@reports_app.route('/view-report', methods=['GET', 'POST'])
@login_required(session)
@role_required(session)
@report_required
def view_report(report):
    if request.method == 'POST':
        check_flag, result = query_execution(
            'date', report['sql_statement'], sql_provider)
        if check_flag:
            cost = sum(item['amount'] * item['price'] for item in result)
            return render_template('view_report.html',
                                   name=report['rep_name'],
                                   rep_id=report['rep_id'],
                                   result=result,
                                   cost=cost)
        else:
            flash(result, 'error')
    return render_template('view_report.html',
                           name=report['rep_name'],
                           rep_id=report['rep_id'])


@reports_app.route('/create-report', methods=['GET', 'POST'])
@login_required(session)
@role_required(session)
@report_required
def create_report(report):
    if request.method == 'POST':
        procedure = report['procedure']
        if not procedure:
            flash('Процедура не найдена', 'error')
            return render_template('create_report.html',
                                   name=report['rep_name'],
                                   rep_id=report['rep_id'])
        date = request.form.get('date')

        result = call_proc(
            current_app.config['MYSQL_DB_CONFIG'], procedure, f'{date}-01')

        if result:
            flash(result, 'error')
        else:
            flash('Отчет успешно создан', 'okay')
    return render_template('create_report.html',
                           name=report['rep_name'],
                           rep_id=report['rep_id'])

templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/static/css/styles.css">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700&display=swap" rel="stylesheet">
    <title>Поставка заготовок</title>
</head>

<body>
    <main>
        <div class="container">
            <div class="container-centered">
                <div class="mytable">
                    <table>
                        <thead>
                            <tr>
                                <th>
                                    <div class="label_page">
                                        Главное меню
                                    </div>
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            {% if session['is_auth'] %}
                            {% if session['role'] == 'logist' or session['role'] == 'merchandiser' %}
                            <tr>
                                <td class="no-padding">
                                    <form action="{{ url_for('queries_app.queries_index') }}" method="GET">
                                        <input type="submit" value="Выполнение запроса">
                                    </form>
                                </td>
                            </tr>
                            {% endif %}
                            {% if session['role'] == 'merchandiser' %}
                            <tr>
                                <td class="no-padding">
                                    <form action="{{ url_for('basket_app.check_invoices') }}" method="GET">
                                        <input type="submit" value="Просмотр накладных">
                                    </form>
                                </td>
                            </tr>
                            {% endif %}
                            {% if session['role'] == 'manager' or session['role'] == 'director' %}
                            <tr>
                                <td class="no-padding">
                                    <form action="{{ url_for('reports_app.reports_index') }}" method="GET">
                                        <input type="submit" value="Работа с отчетами">
                                    </form>
                                </td>
                            </tr>
                            {% endif %}
                            {% if session['role'] == 'external' %}
                            <tr>
                                <td class="no-padding">
                                    <form action="{{ url_for('basket_app.basket_index') }}" method="GET">
                                        <input type="submit" value="Формирование заказа на поставку">
                                    </form>
                                </td>
                            </tr>
                            <tr>
                                <td class="no-padding">
                                    <form action="{{ url_for('access_app.personal_account') }}" method="GET">
                                        <input type="submit" value="Личный кабинет">
                                    </form>
                                </td>
                            </tr>
                            {% endif %}
                            <tr>
                                <td class="no-padding">
                                    <form action="{{ url_for('access_app.logout_handler') }}" method="GET">
                                        <input type="submit" value="Выход">
                                    </form>
                                </td>
                            </tr>
                            {% endif %}
                            {% if not session['is_auth'] %}
                            <tr>
                                <td class="no-padding">
                                    <form action="{{ url_for('access_app.access_index') }}" method="GET">
                                        <input type="submit" value="Авторизация">
                                    </form>
                                </td>
                            </tr>
                            {% endif %}
                        </tbody>
                    </table>
                </div>
            </div>
            {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
            {% for category, message in messages %}
            <div class="message">
                {% if category == 'okay' %}
                <div class="okay">
                    {{ message }}
                </div>
                {% endif %}
                {% if category == 'error' %}
                <div class="error">
                    {{ message }}
                </div>
                {% endif %}
            </div>
            {% endfor %}
            {% endif %}
            {% endwith %}
        </div>
    </main>

    <div id="loading">
        <div class="spinner"></div>
    </div>
</body>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="/static/js/pageEventHandlers.js"></script>

</html>